USE [master]
GO

/****** Object:  Database [sistemAnalizi]    Script Date: 15.06.2021 01:31:47 ******/
CREATE DATABASE [sistemAnalizi]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sistemAnalizi', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\sistemAnalizi.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sistemAnalizi_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\sistemAnalizi_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sistemAnalizi].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sistemAnalizi] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sistemAnalizi] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sistemAnalizi] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sistemAnalizi] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sistemAnalizi] SET ARITHABORT OFF 
GO

ALTER DATABASE [sistemAnalizi] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sistemAnalizi] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sistemAnalizi] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sistemAnalizi] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sistemAnalizi] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sistemAnalizi] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sistemAnalizi] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sistemAnalizi] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sistemAnalizi] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sistemAnalizi] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sistemAnalizi] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sistemAnalizi] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sistemAnalizi] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sistemAnalizi] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sistemAnalizi] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sistemAnalizi] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sistemAnalizi] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sistemAnalizi] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sistemAnalizi] SET  MULTI_USER 
GO

ALTER DATABASE [sistemAnalizi] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sistemAnalizi] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sistemAnalizi] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sistemAnalizi] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sistemAnalizi] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sistemAnalizi] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [sistemAnalizi] SET QUERY_STORE = OFF
GO

ALTER DATABASE [sistemAnalizi] SET  READ_WRITE 
GO
USE [sistemAnalizi]
GO
/****** Object:  Table [dbo].[Files]    Script Date: 15.06.2021 01:30:45 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Files](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[FileBin] [varbinary](max) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Type] [varchar](50) NULL,
	[Size] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

